name: Hadolint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint sync Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: cmd/sync/Dockerfile
      - name: Lint web-ui Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: cmd/web-ui/Dockerfile
